package idemlease_test

import (
	"bytes"
	"context"
	"encoding/hex"
	"errors"
	"fmt"
	"sync"
	"testing"
	"time"

	"github.com/google/go-cmp/cmp"
	"github.com/repenguin22/idemlease"
)

var testOpts = idemlease.Options{LeaseTTL: 30 * time.Second, RecordTTL: time.Hour}

// TestBeginStateTable covers the Begin decision table (REQUIREMENTS
// §3.1, acceptance §12-14) on the fake store.
func TestBeginStateTable(t *testing.T) {
	const key = "k"
	fp := []byte("fp-a")
	otherFP := []byte("fp-b")
	payload := []byte(`{"id":42}`)
	now := time.Now()

	tests := []struct {
		name        string
		seed        *idemlease.Record
		fingerprint []byte
		wantAction  idemlease.Action
	}{
		{
			name:        "no record → Proceed",
			fingerprint: fp,
			wantAction:  idemlease.Proceed,
		},
		{
			name: "expired reserved only → Proceed (overwrite-reserve)",
			seed: &idemlease.Record{
				Key: key, Fingerprint: fp, State: idemlease.StateReserved,
				Token: "stale-token", LeaseExpiresAt: now.Add(-time.Second),
			},
			fingerprint: fp,
			wantAction:  idemlease.Proceed,
		},
		{
			name: "expired completed only → Proceed (overwrite-reserve)",
			seed: &idemlease.Record{
				Key: key, Fingerprint: fp, State: idemlease.StateCompleted,
				Token: "stale-token", Payload: payload,
				RecordExpiresAt: now.Add(-time.Second),
			},
			fingerprint: fp,
			wantAction:  idemlease.Proceed,
		},
		{
			name: "valid reserved, same fingerprint → RejectInFlight",
			seed: &idemlease.Record{
				Key: key, Fingerprint: fp, State: idemlease.StateReserved,
				Token: "holder-token", LeaseExpiresAt: now.Add(20 * time.Second),
			},
			fingerprint: fp,
			wantAction:  idemlease.RejectInFlight,
		},
		{
			name: "valid reserved, different fingerprint → RejectInFlight (decision 7)",
			seed: &idemlease.Record{
				Key: key, Fingerprint: fp, State: idemlease.StateReserved,
				Token: "holder-token", LeaseExpiresAt: now.Add(20 * time.Second),
			},
			fingerprint: otherFP,
			wantAction:  idemlease.RejectInFlight,
		},
		{
			name: "valid completed, same fingerprint → Replay",
			seed: &idemlease.Record{
				Key: key, Fingerprint: fp, State: idemlease.StateCompleted,
				Token: "holder-token", Payload: payload,
				RecordExpiresAt: now.Add(time.Hour),
			},
			fingerprint: fp,
			wantAction:  idemlease.Replay,
		},
		{
			name: "valid completed, different fingerprint → RejectFingerprintMismatch",
			seed: &idemlease.Record{
				Key: key, Fingerprint: fp, State: idemlease.StateCompleted,
				Token: "holder-token", Payload: payload,
				RecordExpiresAt: now.Add(time.Hour),
			},
			fingerprint: otherFP,
			wantAction:  idemlease.RejectFingerprintMismatch,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			st := newFakeStore()
			if tt.seed != nil {
				st.put(*tt.seed)
			}
			before := time.Now()
			out, err := idemlease.Begin(context.Background(), st, key, tt.fingerprint, testOpts)
			after := time.Now()
			if err != nil {
				t.Fatalf("Begin: unexpected error: %v", err)
			}
			if out.Action != tt.wantAction {
				t.Fatalf("Action = %v, want %v", out.Action, tt.wantAction)
			}

			switch tt.wantAction {
			case idemlease.Proceed:
				if out.Token == "" {
					t.Fatal("Proceed outcome must carry a token")
				}
				rec, ok := st.get(key)
				if !ok {
					t.Fatal("Proceed must leave a reserved record in the store")
				}
				if rec.State != idemlease.StateReserved {
					t.Errorf("stored state = %v, want StateReserved", rec.State)
				}
				if rec.Token != out.Token {
					t.Errorf("stored token = %q, want the token returned to the caller %q", rec.Token, out.Token)
				}
				if !bytes.Equal(rec.Fingerprint, tt.fingerprint) {
					t.Errorf("stored fingerprint = %q, want %q", rec.Fingerprint, tt.fingerprint)
				}
				lo, hi := before.Add(testOpts.LeaseTTL), after.Add(testOpts.LeaseTTL)
				if rec.LeaseExpiresAt.Before(lo) || rec.LeaseExpiresAt.After(hi) {
					t.Errorf("LeaseExpiresAt = %v, want within [%v, %v]", rec.LeaseExpiresAt, lo, hi)
				}
			case idemlease.Replay:
				if !bytes.Equal(out.Payload, payload) {
					t.Errorf("Payload = %q, want %q", out.Payload, payload)
				}
			case idemlease.RejectInFlight:
				if out.RetryAfter <= 0 || out.RetryAfter > 20*time.Second {
					t.Errorf("RetryAfter = %v, want within (0, 20s]", out.RetryAfter)
				}
				rec, _ := st.get(key)
				if rec.Token != "holder-token" {
					t.Errorf("in-flight record must be untouched; token = %q", rec.Token)
				}
			}
		})
	}
}

// TestBeginTokenProperties verifies the token contract: generated by
// Begin via crypto/rand, at least 128 bits, unique per reservation.
func TestBeginTokenProperties(t *testing.T) {
	st := newFakeStore()
	seen := make(map[string]bool)
	for i := 0; i < 100; i++ {
		out, err := idemlease.Begin(context.Background(), st, fmt.Sprintf("key-%d", i), nil, testOpts)
		if err != nil {
			t.Fatalf("Begin: %v", err)
		}
		if out.Action != idemlease.Proceed {
			t.Fatalf("Action = %v, want Proceed", out.Action)
		}
		raw, err := hex.DecodeString(out.Token)
		if err != nil {
			t.Fatalf("token %q is not hex: %v", out.Token, err)
		}
		if got := len(raw) * 8; got < 128 {
			t.Fatalf("token is %d bits, want >= 128", got)
		}
		if seen[out.Token] {
			t.Fatalf("duplicate token %q", out.Token)
		}
		seen[out.Token] = true
	}
}

// TestBeginStoreFailure verifies that a Reserve failure surfaces as
// Begin's error (fail-open/closed interpretation is the caller's job).
func TestBeginStoreFailure(t *testing.T) {
	st := newFakeStore()
	boom := errors.New("store down")
	st.reserveErr = boom

	out, err := idemlease.Begin(context.Background(), st, "k", nil, testOpts)
	if !errors.Is(err, boom) {
		t.Fatalf("err = %v, want the injected store error", err)
	}
	if diff := cmp.Diff(idemlease.Outcome{}, out); diff != "" {
		t.Errorf("Outcome must be the zero value on error (-want +got):\n%s", diff)
	}
}

// TestBeginStoreMisbehavior verifies that contract violations by the
// store are reported as errors instead of being misread as decisions.
func TestBeginStoreMisbehavior(t *testing.T) {
	t.Run("ErrAlreadyExists without existing record", func(t *testing.T) {
		st := &stubStore{existing: nil, err: idemlease.ErrAlreadyExists}
		if _, err := idemlease.Begin(context.Background(), st, "k", nil, testOpts); err == nil {
			t.Fatal("want error, got nil")
		}
	})
	t.Run("existing record with invalid state", func(t *testing.T) {
		st := &stubStore{
			existing: &idemlease.Record{Key: "k"}, // zero State is invalid
			err:      idemlease.ErrAlreadyExists,
		}
		if _, err := idemlease.Begin(context.Background(), st, "k", nil, testOpts); err == nil {
			t.Fatal("want error, got nil")
		}
	})
}

// TestBeginConcurrentSameKey hammers one key from 100 goroutines and
// checks that exactly one wins the lease (§10, run with -race).
func TestBeginConcurrentSameKey(t *testing.T) {
	st := newFakeStore()
	fp := []byte("fp")
	const n = 100

	actions := make([]idemlease.Action, n)
	errs := make([]error, n)
	var wg sync.WaitGroup
	for i := 0; i < n; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			out, err := idemlease.Begin(context.Background(), st, "same-key", fp, testOpts)
			actions[i], errs[i] = out.Action, err
		}(i)
	}
	wg.Wait()

	var proceeds, inflights int
	for i := 0; i < n; i++ {
		if errs[i] != nil {
			t.Fatalf("Begin #%d: %v", i, errs[i])
		}
		switch actions[i] {
		case idemlease.Proceed:
			proceeds++
		case idemlease.RejectInFlight:
			inflights++
		default:
			t.Fatalf("Begin #%d: unexpected action %v", i, actions[i])
		}
	}
	if proceeds != 1 || inflights != n-1 {
		t.Fatalf("proceeds = %d, inflights = %d; want 1 and %d", proceeds, inflights, n-1)
	}
}
