package idemlease

import "time"

// State is the persisted state of a Record.
type State uint8

const (
	// StateReserved marks an in-flight execution holding the lease.
	// The zero State is invalid so that uninitialized records are caught.
	StateReserved State = iota + 1
	// StateCompleted marks a finished execution whose payload is stored.
	StateCompleted
)

// Record is the unit persisted by a Store. The core treats Key,
// Fingerprint, and Payload as opaque values: it neither interprets nor
// validates them (key grammar, fingerprint algorithms, and payload
// encodings belong to callers such as httpidem).
type Record struct {
	// Key identifies the record. The core does not limit its length.
	Key string
	// Fingerprint identifies the request that created the record.
	Fingerprint []byte
	// State is StateReserved or StateCompleted.
	State State
	// Token is the reservation token generated by Begin (crypto/rand,
	// at least 128 bits). Stores persist and compare it verbatim.
	Token string
	// LeaseExpiresAt bounds the in-flight execution: a reserved record
	// at or past this instant is logically absent.
	LeaseExpiresAt time.Time
	// RecordExpiresAt bounds replay: a completed record at or past this
	// instant is logically absent. It is zero while reserved and is set
	// by Complete.
	RecordExpiresAt time.Time
	// Payload is the stored result, set when State is StateCompleted.
	Payload []byte
}

// Expired reports whether the record is logically absent at now:
// reserved records expire at LeaseExpiresAt, completed records at
// RecordExpiresAt. The boundary instant itself counts as expired, and
// records in an unknown state are always expired.
func (r Record) Expired(now time.Time) bool {
	switch r.State {
	case StateReserved:
		return !now.Before(r.LeaseExpiresAt)
	case StateCompleted:
		return !now.Before(r.RecordExpiresAt)
	default:
		return true
	}
}
